# 1. Create a 3x3x3 array with random values

In [39]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[0.04823727 0.10319532 0.93908671]
  [0.90345262 0.76575697 0.22849953]
  [0.7981839  0.62586047 0.73820396]]

 [[0.03697809 0.17605137 0.91372245]
  [0.14926825 0.10096757 0.1082537 ]
  [0.55679903 0.70018393 0.50546446]]

 [[0.4976322  0.73683121 0.43044025]
  [0.83449637 0.68474577 0.04464144]
  [0.90192659 0.85564582 0.00285997]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [40]:
import numpy as np
arr = np.diag(np.arange(4)+1, k = -1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [41]:
import numpy as np
print("Checkerboard pattern:")
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [42]:
import numpy as np
arr = np.random.random((5,5))
arrmax, arrmin = arr.max(), arr.min()
arr= (arr-arrmin)/(arrmax-arrmin)
print (arr)

[[0.         0.04272693 0.2524306  0.40398965 0.58581636]
 [0.21779928 0.71698191 0.52382399 0.44589637 0.50368399]
 [0.36357054 0.7668773  0.11407011 1.         0.61752341]
 [0.85281721 0.9664379  0.21278908 0.98165214 0.78351894]
 [0.45080787 0.77498863 0.2929573  0.61629239 0.43500127]]


# 5.  How to find common values between two arrays?

In [43]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [44]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [45]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Checking above two arrays are equal or not")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1 1 0 0]
Second array:
[0 0 1 0 1 0]
Checking above two arrays are equal or not
False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [46]:
import numpy as np
arr = np.random.random(10)
arr[arr.argmax()] = 0
print(arr)

[0.98022358 0.02195717 0.         0.17366724 0.63703904 0.34155701
 0.01192874 0.80625924 0.81150727 0.7020786 ]


# 9. How to print all the values of an array?

In [47]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [48]:
import numpy as np
print("Original matrix:\n")
X = np.random.randint(1,20,size =(3,4))
print(X)
print("\nSubtract the mean of each row of the above matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[ 1 19  5 18]
 [ 4 14 11 19]
 [ 7  4 17 19]]

Subtract the mean of each row of the above matrix:

[[-9.75  8.25 -5.75  7.25]
 [-8.    2.   -1.    7.  ]
 [-4.75 -7.75  5.25  7.25]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [49]:
import numpy as np
a1 = np.ones(10)
b1 = np.random.randint(0,len(a1),20)
a1 += np.bincount(b1, minlength=len(a1))
print(a1)

[2. 2. 4. 3. 4. 4. 1. 2. 3. 5.]


# 12.How to get the diagonal of a dot product?

In [50]:
import numpy as np
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
print(A)
print("\n")
print(B)
print("\n")
print(np.dot(A,B))
print("\ndiagonal is ")
np.diag(np.dot(A, B))

[[3 1 9]
 [2 3 2]
 [7 2 5]]


[[9 5 5]
 [4 3 9]
 [0 7 1]]


[[31 81 33]
 [30 33 39]
 [71 76 58]]

diagonal is 


array([31, 33, 58])

# 13.How to find the most frequent value in an array?

In [51]:
import numpy as np
arr = np.random.randint(0,10,50)
print (arr)
print("\n")
print('most frequent value is:', np.bincount(arr).argmax())

[4 9 6 2 5 8 1 1 5 3 3 1 0 8 5 2 8 4 8 8 3 1 3 7 4 5 7 9 4 0 2 9 2 0 8 7 4
 5 7 1 4 5 5 4 3 1 3 2 8 1]


most frequent value is: 1


# 14.How to get the n largest values of an array

In [54]:
import numpy as np
arr =int(input("How many array size required "))
n = int(input("Enter n value "))
import numpy as np
x = np.arange(arr)
print("array is:")
print(x)
np.random.shuffle(x)
#n = 1
print (n,"Largest values in an array is ",x[np.argsort(x)[-n:][::-1]])

How many array size required 50
Enter n value 4
array is:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
4 Largest values in an array is  [49 48 47 46]


# 15.How to create a record array from a regular array?

In [55]:
import numpy as np
arra1 = np.array([("Bat", 88.5, 90),
                 ("Cat", 87, 99),
             ("Hat", 85.5, 91)])
print("Original array:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original array:
[['Bat' '88.5' '90']
 ['Cat' '87' '99']
 ['Hat' '85.5' '91']]

Record array;
[(b'Bat', 88.5, 90) (b'Cat', 87. , 99) (b'Hat', 85.5, 91)]
